#+title: Dynamical Regimes of Thalamocortical Activity: Insights from Theoretical Models of Spiking Networks
#+author: Y.Zerlaut

** Abstract

We review here the literature on network dynamics of spiking units with an emphasis on the dynamical regime. We compare those recordings with the 

We highlight how different models 

** Introduction

Given the strong ongoing activity characterizing thalamo-cortical
activity, understanding the dynamical regimes of brain activity is a
key step to unveil cortical function.

In particular recent analysis of recurrent dynamics in spiking
networks call for the needs of clarification / standardization of the
terminology of the recurrent dynamics.


** Dynamical Regimes in Spiking Networks

*** Spiking Activity in Neural Networks: Synchrony, Regularity and Rhythmicity

What are the quantities defining the dynamical regime of 

A seminal study introduced synchrony and regularity to characterize recurrent dynamics (Brunel, 2000). 

We argue here that, for a broader view on recurrent dynamics, there is the need to add the concept of "rhythmicity". 

The definition of those three terms are the following:

- Regularity: property of a single neuron spiking over time

- Synchrony: property of pairwise interaction to simultaneously fire together

- Rhythmicity: tendency of the population to phase-lock to a given oscillation

The reason behind this classification is that activity can be:

- Irregular, Asynchronous, Non-Rhythmic (fully desynchronized activity, e.g. high-arousal wakefulness)
- Irregular, Synchronous, Non-Rhythmic (stochastic Up & Down states, e.g. deep anesthesia)
- Irregular, Synchronous, Rhythmic (regular Up & Down states dynamics, e.g. SWS)
- Regular, Synchronous, Rhythmic (Epilespy)
- Regular, asynchronous, Rhythmic (Epilespy)

Not possible:
- Regular, Synchronous, Non-Rhythmic (non-rhythmicity implies irregularity)


*** Asynchronous Activity

An ideality on which we build upon to understand.

There is always residual sychrony. Finding a good criteria to consider the dynamics aysnchronous (at a given scale ?): ??

**** Mechanisms behind asynchronous activity

- Inherited asynchrony: spontaneous synaptic release, inherited from afferent brain regions

- Interaction-mediated asynchrony: unreliability of synaptic transmission destroying synchronization, ...

- An emergent solutions of recurrent activity in balanced networks. Self-sustained asynchronous activity shows that 

Those different sources of asynchrony are not exclusive and can co-exist within the same network (cf CellRep, ...). Indeed, several studies use those mechanisms together to .

*** Sources of Synchrony

- Finite-Size Effects & Connectivity-based Mechanisms

- Stochastic Transitions in multi-stable systems

*** Sources of Rhytmicity

- Pacemaker-like biophysical mechanisms

- Network loops

**** Weak synchrony: fast oscillation

**** Strong synchrony: slow rhythm, finite size effects 

***** Strong synchrony: slow rhythm


** Experimental Characterization of Thalamocortical Dynamics

*** Intracellular recordings

Because a cortical neuron receives inputs from underds to thousands of
its neighbors, the intracellular dynamics offers an particular readout
of

*** Extracellular recordings

*** Perturbations 1: sensory stimuli

*** Perturbations 2: Electrical and optogenetic stimulation


** Regimes of Sleep

** Regimes of Wakefulness

** Discussion

We reviewed here

Future work should focus on 

** References


